# This GitHub action will auto-assign the PR author as an assignee and will not override the assignee if it's already assigned manually.

name: Assign Author
on: [pull_request]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
    - uses: technote-space/assign-author@v1.3.1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
